name: "wf1"

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "This is workflow 1"