name : "tt"

on:
  push:
    branches:
      - main
    

jobs:
t1:
steps:

    - name: "tt2"
      run: echo "tt3"
    - name: "tt4"
      run: echo "tt5"
    - name: "tt6"
      run: echo "tt7"
    - name: "tt8"
      run: echo "tt9"